# Lasso Regularization

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.linear_model import Lasso

In [14]:
data = load_diabetes()
df = pd.DataFrame(data.data, columns=data.feature_names)

In [15]:
df.head()

        age       sex  ...        s5        s6
0  0.038076  0.050680  ...  0.019907 -0.017646
1 -0.001882 -0.044642  ... -0.068332 -0.092204
2  0.085299  0.050680  ...  0.002861 -0.025930
3 -0.089063 -0.044642  ...  0.022688 -0.009362
4  0.005383 -0.044642  ... -0.031988 -0.046641

[5 rows x 10 columns]

In [16]:
df['target'] = data.target

In [18]:
x, y = data.data, data.target

In [21]:
alphas = [0,0.0001,0.001,0.01,0.1,1,10,100,1000,10000]
coef = []

for i in alphas:
    l = Lasso(alpha=i)
    l.fit(x, y)
    coef.append(l.coef_.tolist())

D:\machine learning\myenv\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
D:\machine learning\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
D:\machine learning\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.320e+05, tolerance: 2.621e+02
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

In [28]:
df_coef = pd.DataFrame(coef, index=alphas, columns=data.feature_names)

In [29]:
df_coef

                  age  ...         s6
0.0000     -10.009866  ...  67.626692
0.0001      -9.908491  ...  67.611706
0.0010      -8.996177  ...  67.476810
0.0100      -1.304662  ...  65.008383
0.1000      -0.000000  ...  33.673965
1.0000       0.000000  ...   0.000000
10.0000      0.000000  ...   0.000000
100.0000     0.000000  ...   0.000000
1000.0000    0.000000  ...   0.000000
10000.0000   0.000000  ...   0.000000

[10 rows x 10 columns]